### ISSUE TITLE
Dab miniv3 not updating data

### ISSUE THREAD

**Issue by Deedzy** [ankohanse/hass-dab-pumps#13]
After the update tp2024.3.2 the data isn't updating.

New error
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:352
Integration: Sensor (documentation, issues)
First occurred: 12:07:47 pm (1 occurrences)
Last logged: 12:07:47 pm

Error while setting up dabpumps platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 352, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 533, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 782, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1325, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 989, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1110, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1047, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 995, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 558, in state
    raise ValueError(
ValueError: Sensor sensor.esybox_mini_v3_samplerate has a unit of measurement and thus indicating it has a numeric value; however, it has the non-numeric device class: enum

**Comment by ankohanse** [comment]
Lucklily an easy fix. Now available in release v2024.03.3

I've had to change a lot of code to support new functionaly for PowerShower and SleepMode. So more bugs may popup for other pumps that I did not find with my ESybox.
Just keep reporting them as they come up and I'll fix them as soon as possible.
