### ISSUE TITLE
Cannot get past the GUI configuration

### ISSUE THREAD

**Issue by ankohanse** [ankohanse/hass-dab-pumps#15]
[Bug report on behalf of Nico Pretorius]
I see the following in the log when I run the config to add my credentials after adding the integration:

2024-03-08 08:46:50.545 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
resp = await request_handler(request)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
resp = await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 91, in security_filter_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 25, in request_context_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
response = await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 68, in handle
result = await handler(request, **request.match_info)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 72, in with_admin
return await func(self, request, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 197, in post
return await super().post(request, flow_id)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
result = await method(view, request, data, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 111, in post
result = await self._flow_mgr.async_configure(flow_id, data)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 359, in async_configure
result = await self._async_configure(flow_id, user_input)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 405, in _async_configure
result = await self._async_handle_step(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 502, in _async_handle_step
result: FlowResult = await getattr(flow, method)(user_input)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/dabpumps/config_flow.py", line 101, in async_step_user
await self.async_try_connection()
File "/config/custom_components/dabpumps/config_flow.py", line 69, in async_try_connection
coordinator = DabPumpsCoordinatorFactory.create_temp(self._username, self._password)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/dabpumps/coordinator.py", line 109, in create_temp
api = DabPumpsApiFactory.create(hass, username, password)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/dabpumps/api.py", line 62, in create
api = DabPumpsApi(hass, username, password)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/dabpumps/api.py", line 87, in __init__
self._hass.async_create_task(self._history_store.async_remove())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'async_create_task'
Let me know if you prefer that I open issue on [Issues · ankohanse/hass-dab-pumps · GitHub](https://github.com/ankohanse/hass-dab-pumps/issues).

Below my current HA versions which are all on the latest version available:

Core 2024.3.0
Supervisor 2024.02.1
Operating System 12.0
Frontend 20240306.0

**Comment by ankohanse** [comment]
Thank you, that log is very helpful. At first glance looks like a bug introduced by me in code that gathers more debug information.

Will come up with a fix as soon as possible, probably before the end of the weekend.

**Comment by nicopret1** [comment]
Thank you for your quick response @ankohanse. I'm looking forward to using your DAB integration. Please let me know if you need anything else.

**Comment by ArndtHA** [comment]
Same Problem for me. I have a DAB E.sybox Mini.

**Comment by ankohanse** [comment]
Just published a solution for this bug in release v2024.03.4

This part is hard for me to test, once you got the integration configured it is not used anymore. So please let me know if you run in any new issues.

**Comment by nicopret1** [comment]
Thank you @ankohanse. The problem is fixed and my DAB integration is working now with my EasyBoxMini3.

**Comment by ArndtHA** [comment]
THX, works now perfect.
