### ISSUE TITLE
Error handling request

### ISSUE THREAD

**Issue by Djavdeteg** [ankohanse/hass-dab-pumps#2]
During the first configuration step:
![chrome_dqdFDyNnlj](https://github.com/ankohanse/hass-dab-pumps/assets/111967435/d9aee930-26cb-4139-b7a9-7843af548fe1)

`Logger: aiohttp.server
Source: /usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py:421
First occurred: 09:32:46 (1 occurrences)
Last logged: 09:32:46

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 233, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 149, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 63, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 177, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 293, in async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 389, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dabpumps/config_flow.py", line 94, in async_step_user
    await self.async_try_connection()
  File "/config/custom_components/dabpumps/config_flow.py", line 67, in async_try_connection
    self._install_map = await dabpumpsapi.async_detect_installs()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dabpumps/dabpumpsapi.py", line 81, in async_detect_installs
    await self._async_detect(None)
  File "/config/custom_components/dabpumps/dabpumpsapi.py", line 98, in _async_detect
    success = await self._async_fetch_installs()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dabpumps/dabpumpsapi.py", line 237, in _async_fetch_installs
    device_id = DabPumpsApi.create_id(dum.get('name', ''), suffix_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dabpumps/dabpumpsapi.py", line 349, in create_id
    str = '_'.join(args).strip('_')
          ^^^^^^^^^^^^^^
TypeError: sequence item 0: expected str instance, NoneType found
`

**Comment by ankohanse** [comment]
Thanks for reporting that. The json data returned by DAB Pumps for your installation had a 'null' value for the 'name' property.
I've now made that part of the code more robust with regards to missing values and it will fall back on to alternative properties.

There is a new release v2023.12.2 available if you would want to test again.
If you copied the files manually, you only need to replace the 'dabpumpsapi.py' file.
If you used a HACS custom integration, then I am actually not sure how to trigger it to retrieve the new code files. You might need to remove the custom integration and then add it again.

If you have a chance of testing again using the new version, then please let me know if that completely solves the issue or if a next issue now pops up.

**Comment by Djavdeteg** [comment]
Nice.
Works like a charm now.
Thank you!
