### ISSUE TITLE
Error doing job: Task exception was never retrieved

### ISSUE THREAD

**Issue by jrkk0925** [ankohanse/hass-dab-pumps#25]
Getting lot of these errors.

System information
Version	core-2024.4.1
Installation Type	Home Assistant OS

Home Assistant Supervisor
Host Operating System	Home Assistant OS 12.1
Update Channel	stable
Supervisor Version	supervisor-2024.03.1

Logger: homeassistant
Source: helpers/storage.py:286
First occurred: 7:19:10 AM (88 occurrences)
Last logged: 7:34:11 AM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/dabpumps/api.py", line 503, in _async_worker
    data = await self._history_store.async_load() or {}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dabpumps/api.py", line 569, in async_load
    data = await super().async_load() or {}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 294, in async_load
    return await load_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 303, in _async_load
    return await self._async_load_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 415, in _async_load_data
    await self.async_save(stored)
  File "/config/custom_components/dabpumps/api.py", line 577, in async_save
    data = await super().async_load() or {}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 286, in async_load
    return await self._load_task
           ^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Task cannot await on itself: <Task pending name='Storage load dabpumps.api_history' coro=<Store._async_load() running at /usr/src/homeassistant/homeassistant/helpers/storage.py:303> cb=[set.remove(), Task.task_wakeup()]>

**Comment by ankohanse** [comment]
Thanks for reporting this.
Fixed in v2024.04.2 that I published just now
